### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by cjprall** [cdzombak/groupme-tools#7]
So I don't know much about Python, but when running simple-transcript.py I get the following error
![image](https://cloud.githubusercontent.com/assets/9115517/8138490/433b46fc-1119-11e5-8b52-0dca3035cbae.png)
I'm using Python 2.7.10 on Windows 8.1 64-bit

Any advice?

**Comment by cdzombak** [comment]
https://github.com/cdzombak/groupme-tools/issues/2 may be useful here, but I am not familiar with Python's unicode handling on Windows and can't provide any more help. Sorry!

**Comment by bshaibu** [comment]
I don't appear to have permissions to create a PR, but a fix for this would be something along the lines 
of changing simple-transcript.py to have:

        string = system_padded + name + ' (' + time + ')' + favorites_padded + ': ' + text + pic
        print(string.encode(sys.stdout.encoding, errors='replace'))

This makes the string's encoding system dependent.

**Comment by cdzombak** [comment]
@cjprall Try again now that I've merged #8?

**Comment by cjprall** [comment]
@cdzombak That fixed it! But I think I prefer @bshaibu's fix to output to a file, since the content is just more navigable that way.
